CREATE TABLE MsUser
(
	UserID UNIQUEIDENTIFIER PRIMARY KEY,
	UserName VARCHAR(50) NOT NULL,
	UserPassword VARCHAR(50) NOT NULL,
	UserNickName VARCHAR(50) NOT NULL,
);

ALTER TABLE MsUser
ADD UserRole INT NOT NULL

ALTER TABLE MsUser
ADD UserIn VARCHAR(50), DateIn DATE, UserUp VARCHAR(50), DateUp DATE

ALTER TABLE MsUser
ALTER COLUMN DateIn DATETIME
ALTER TABLE MsUser
ALTER COLUMN DateUp DATETIME
--INSERT INTO MsUser
--VALUES (NEWID(), 'DummyUser', 'DummyPass','Dummy', 1)


CREATE TABLE MsUserRole
(
	UserRoleID UNIQUEIDENTIFIER PRIMARY KEY,
	UserRole INT NOT NULL,
	UserRoleStatus VARCHAR(50) NOT NULL,
	UserIn VARCHAR(50), 
	DateIn DATETIME, 
	UserUp VARCHAR(50), 
	DateUp DATETIME
);